language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("POMCP");'
  - julia -e 'Pkg.clone("https://github.com/sisl/POMDPs.jl"); Pkg.clone("https://github.com/sisl/POMDPModels.jl"); Pkg.clone("https://github.com/sisl/POMDPToolbox.jl"); Pkg.clone("https://github.com/sisl/POMDPDistributions.jl");'
  - julia --check-bounds=yes -e 'Pkg.test("POMCP"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("POMCP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
